---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.COP_UI_NAME}}
  labels:
    service: {{.COP_UI_NAME}}
spec:
  selector:
    matchLabels:
      name: {{.COP_UI_NAME}}
  replicas: 3
  revisionHistoryLimit: 3
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        name: {{.COP_UI_NAME}}
        service: {{.WORKFLOW_UI_NAME}}
    spec:
      restartPolicy: Always
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
      containers:
      - name: {{.COP_UI_NAME}}
        image: {{.COP_UI_IMAGE}}:{{.COP_UI_TAG}}
        imagePullPolicy: Always
        securityContext:
          runAsUser: 1000
          runAsNonRoot: true
        command: ["/bin/sh"]
        args: ["-c", "/app/run.sh -Djava.security.egd=file:/dev/./urandom -Djavax.net.ssl.keyStore=/etc/keystore/keystore.p12 -Djavax.net.ssl.keyStorePassword=changeit -Djavax.net.ssl.trustStore=/etc/keystore/cacerts -Djavax.net.ssl.trustStoreType=pkcs12 -Djavax.net.ssl.trustStorePassword=changeit -jar /app/{{ .COP_UI_NAME }}.jar"]
        resources:
          requests:
            memory: "1024Mi"
            cpu: "1000m"
          limits:
            memory: "1024Mi"
            cpu: "1000m"
        ports:
          - name: https
            containerPort: 8443
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8443
            scheme: HTTPS
          initialDelaySeconds: 30
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /actuator/info
            port: 8443
            scheme: HTTPS
          initialDelaySeconds: 30
          periodSeconds: 10
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: "{{.SPRING_PROFILES_ACTIVE}}"
          - name: AWS_REGION
            value: "{{.AWS_REGION}}"
          - name: AWS_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: {{.COP_UI_NAME}}
                key: awsAccessKeyId
          - name: AWS_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: {{.COP_UI_NAME}}
                key: awsSecretAccessKey
          - name: AWS_SECRETS_MANAGER_ENABLED
            value: "{{.AWS_SECRETS_MANAGER_ENABLED}}"
        volumeMounts:
          - name: certs
            mountPath: /certs
            readOnly: true
      volumes:
      - name: certs
        secret:
          secretName: "{{.COP_UI_NAME}}-pod-cmio"
