# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: COP UI CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test-ui-server:
   runs-on: ubuntu-latest
   steps:
   - uses: actions/checkout@v2
   - uses: joschi/setup-jdk@v1
     with:
      java-version: 'openjdk14'
      architecture: 'x64'
   - name: Grant execute permission for gradlew
     run: chmod +x gradlew
   - name: Run tests
     run: ./gradlew clean test

  test-react-ui:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      working-directory: ./client
      run: npm install
    - name: Run tests with coverage
      working-directory: ./client
      run: npm run test-coverage
      env:
        CI: true
